apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "terralist.fullname" . }}-config
  labels:
    {{- include "terralist.labels" . | nindent 4 }}
data:
  config.yaml: |
    log:
      level: debug
    
    database:
      backend: sqlite
      sqlite:
        path: /data/terralist.db
    
    server:
      host: 0.0.0.0
      port: 5758
      url: https://terralist.caas.k-mkaas-dev-1.cloud.preprod.world
    
    auth:
      oauth:
        provider: oidc
        oidc:
          scope: "openid email profile"
          client_id: {{ .Values.config.auth.oauth.clientId | quote }}
          client_secret: {{ .Values.config.auth.oauth.clientSecret | quote }}
          authorize_url: "{{ .Values.config.auth.oauth.issuerUrl }}/protocol/openid-connect/auth"
          token_url: "{{ .Values.config.auth.oauth.issuerUrl }}/protocol/openid-connect/token"
          userinfo_url: "{{ .Values.config.auth.oauth.issuerUrl }}/protocol/openid-connect/userinfo"
      
      cookie_secret: {{ .Values.config.auth.cookieSecret | quote }}
      token_signing_secret: {{ .Values.config.auth.tokenSigningSecret | quote }}
    
    modules:
      anonymous_read: true
    
    storage:
      backend: s3
      s3:
        endpoint: s-ed1.cloud.gcore.lu
        bucket_name: terralist-artifacts
        bucket_region: eu-central-1
        access_key_id: BVQO6XXVBZAB6EYQX02G
        secret_access_key: jlObBtZA7aJ7Gzx2b2vhzfK1MgrcS495Q5ChR3La
        use_path_style: true
        presign_expire: 15m